IstanbulNsApp/IstanbulNsApp/ViewModels/DoctorViewModel.cs
using IstanbulNsApp.Resources.DTO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace IstanbulNsApp.ViewModels
{
    public class DoctorViewModel
    {
        public List<DoctorDTO> Data { get; set; }
        public int? Number { get; set; }
    }
}

IstanbulNsApp/IstanbulNsApp/Controllers/ServicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using IstanbulNsApp.Libs;
using IstanbulNsApp.Resources.DTO;
using IstanbulNsApp.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;

namespace IstanbulNsApp.Controllers
{
    public class ServicesController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IConfiguration _config;
        private readonly HttpClient _fc;
        public ServicesController(ILogger<HomeController> logger, IConfiguration config, IHttpClientFactory fc)
        {
            _logger = logger;
            _config = config;
            _fc = fc.CreateClient(name: "ApiRequests");
            _config = config;
        }
        public async Task<IActionResult> Index([FromQuery] int serve)
        {
            int langId = 1;
            int serviceId = 1;
            if (serve!=null)
            {
                serviceId = serve;
            }
            if (Request.Cookies["LangKey"] != null)
            {
                langId = Convert.ToInt32(Request.Cookies["LangKey"]);
            }
            var modal = await new ServiceNodeAsync<object, ServiceInfo>(_fc).GetClientAsync("/api/services/info/"+langId+"/"+serviceId);
            return View(modal.Data);
        }
        public async Task<IActionResult> AllServices()
        {
            int langId = 1;
            if (Request.Cookies["LangKey"] != null)
            {
                langId = Convert.ToInt32(Request.Cookies["LangKey"]);
            }
            var modal = await new ServiceNodeAsync<object, List<ServiceInfoMini>>(_fc).GetClientAsync("/api/services/all/" + langId);
            return View(modal.Data);
        }
        public async Task<IActionResult> Doctors([FromQuery] int page)
        {
            int pagecount = 0;
            if (page is object)
            {
                pagecount = page;
            }
            var services = await new ServiceNodeAsync<object, DoctorViewModel>(_fc).GetClientAsync("/api/doctors/all/" + pagecount);
            return View(services.Data);

        }
        public async Task<IActionResult> DoctorsPartial([FromQuery] int page)
        {
            int pagecount = 0;
            if (page is object)
            {
                pagecount = page;
            }
            var services = await new ServiceNodeAsync<object, DoctorViewModel>(_fc).GetClientAsync("/api/doctors/all/" + pagecount);
            return View(services.Data);

        }
        public async Task<IActionResult> DoctorsInfo([FromQuery] int doctor)
        {
            int doctorId = 0;
            if (doctor > 0)
            {
                doctorId = doctor;
            }
            int langId = 1;

            if (Request.Cookies["LangKey"] != null)
            {
                langId = Convert.ToInt32(Request.Cookies["LangKey"]);
            }
            var services = new ServiceNode<object, DoctorInfoDTO>(_fc).GetClient("/api/doctors/info/" + doctorId+"/"+langId);
            return View(services.Data);

        }
        public async Task<IActionResult> DoctorFind([FromQuery] string st)
        {
            string first = string.Empty;
            if (st is object)
            {
                first = st;
            }
            var services = await new ServiceNodeAsync<object, DoctorViewModel>(_fc).GetClientAsync("/api/doctors/find/" + first);
            return View("Doctors",services.Data);

        }



    }
}

IstanbulNsApp/IstanbulNsApp/ViewComponents/ServicesViewComponent.cs
using IstanbulNsApp.Libs;
using IstanbulNsApp.Resources.DTO;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;

namespace IstanbulNsApp.ViewComponents
{
    public class ServicesViewComponent :ViewComponent
    {
        private readonly HttpClient _fc;
        private readonly IConfiguration _config;
        public ServicesViewComponent(IHttpClientFactory fc, IConfiguration config)
        {
            _fc = fc.CreateClient(name: "ApiRequests");
            _config = config;

        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            int langId = 1;

            if (Request.Cookies["LangKey"] != null)
            {
                langId = Convert.ToInt32(Request.Cookies["LangKey"]);
            }
            var client = new ServiceNodeAsync<object, List<ServiceDTO>>(_fc);
            var services = await client.GetClientAsync("/api/services/services/" + langId);
            return View(services.Data.OrderBy(a =>a.Id));
        }
    }
}

IstanbulNsApp/IstanbulNsApp/Views/Services/AllServices.cshtml
 <!-- End Header -->
@model List<IstanbulNsApp.Resources.DTO.ServiceInfoMini>
<div id='dle-content'>
    <link rel="stylesheet" href="../use.fontawesome.com/releases/v5.7.2/css/all.css"
          integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link rel="stylesheet" href="~/indexlayout/css/shobeler.css">

    <section id="doctor-main">
        <div class="overlay-service"></div>
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="section-heading">
                        <h3>TƏDBİRLƏR</h3>
                    </div>
                </div>
            </div>
        </div>
    </section>




    <section id="more-event">
        <div class="container-fluid">
            <div class="container">
                <div class="row">
                    <div class="col-lg-3 col-md-4 col-sm-12 col-12">
                        @await Component.InvokeAsync("Services")
                    </div>

                    <div class="col-lg-9 col-md-8 col-sm-12 col-12 mb-5">
                        <div class="departments">

                            <p>
                                İstanbul NS Klinikası çoxprofilli tibb müəssisəsidir. Onun ambulator və stasionar
                                bölmələrində böyüklərə və uşaqlara diaqnostik və tibbi yardım xidmətlərinin göstərilməsi
                                üçün bütün lazımi şöbələr mövcuddur. Hər bir şöbənin səhifəsini açıb onun fəaliyyəti və
                                orada çalışan tibb işçiləri ilə tanış ola biləsiniz.
                            </p>
                        </div>

                        <div class="row">
                            @foreach (var item in Model)
                            {
                                <div class="col-lg-4 col-md-6 col-sm-6 col-12">
                                    <div class="about-department">
                                        <a href="anesteziologiya-ve-reanimasiya.html">
                                            <div class="overlay"></div>
                                            @if (item.Picture is null)
                                            {
                                                <img class="w-100" src="~/indexlayout/uploads/posts/2020-02/1582026072_whatsapp-image-2020-02-04-at-14.54.03.jpg" alt="Damar Cərrahiyyəsi">
                                                //<img src="~/indexlayout/images/notfoundpicture.jpg" alt="@item.Name">
                                            }
                                            else
                                            {
                                                <img src="~/indexlayout/images/@item?.Picture" alt="@item?.Name">
                                            }

                                        </a>

                                        <h3>
                                            <a asp-action="Index" asp-controller="Services" asp-route-serve="@item?.Id">@item?.Name</a>
                                        </h3>
                                    </div>
                                </div>
                            }







                        </div>
                    </div>
                </div>
            </div>
        </div>

        
    </section>

IstanbulNsApp/IstanbulNsApp/Views/Services/Doctors.cshtml
@model IstanbulNsApp.ViewModels.DoctorViewModel


<div id='dle-content'>
    <link rel="stylesheet" href="~/indexlayout/css/hekimlerimiz.css">
    <section id="doctor-main">
        <div class="overlay-service"></div>
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="section-heading">
                        <h3>HƏKİMLƏRİMİZ</h3>
                        <span class="text-white">(əlifba sırası ilə)</span>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section id="doctors">
        <div class="hekimlerimiz">
            <div class="container">
                <div class="text-center">
                    <p>
                        Yüksək ixtisaslı, təcrübəli və qayğıkeş həkimlərimiz sağlamlığınızın qorunması üçün sizə
                        keyfiyyətli tibbi yardım göstərməyə hər zaman hazırdır! Onların qəbuluna saytımızdan yazıla
                        bilərsiniz.
                    </p>
                </div>
                <input type="hidden" id="numberofpages" value="@Model?.Number" />
                <div class="row">
                    <div class="col-lg-1 col-md-1 col-1">
                        <a class="alphabet" asp-action="DoctorFind" asp-controller="Services" asp-route-st="a">A</a>
                    </div>
                    <div class="col-lg-1 col-md-1 col-1">
                        <a class="alphabet" asp-action="DoctorFind" asp-controller="Services" asp-route-st="b">B</a>
                    </div>
                    <div class="col-lg-1 col-md-1 col-1">
                        <a class="alphabet" asp-action="DoctorFind" asp-controller="Services" asp-route-st="c">C</a>
                    </div><div class="col-lg-1 col-md-1 col-1">
                        <a class="alphabet" asp-action="DoctorFind" asp-controller="Services" asp-route-st="ç">Ç</a>
                    </div>
                    <div class="col-lg-1 col-md-1 col-1">
                        <a class="alphabet" asp-action="DoctorFind" asp-controller="Services" asp-route-st="d">D</a>
                    </div><div class="col-lg-1 col-md-1 col-1">
                        <a class="alphabet" asp-action="DoctorFind" asp-controller="Services" asp-route-st="e">E</a>
                    </div>
                    <div class="col-lg-1 col-md-1 col-1">
                        <a class="alphabet" asp-action="DoctorFind" asp-controller="Services" asp-route-st="ə">Ə</a>
                    </div><div class="col-lg-1 col-md-1 col-1">
                        <a class="alphabet" asp-action="DoctorFind" asp-controller="Services" asp-route-st="f">F</a>
                    </div><div class="col-lg-1 col-md-1 col-1">
                        <a class="alphabet" asp-action="DoctorFind" asp-controller="Services" asp-route-st="g">G</a>
                    </div><div class="col-lg-1 col-md-1 col-1">
                        <a class="alphabet" asp-action="DoctorFind" asp-controller="Services" asp-route-st="h">H</a>
                    </div><div class="col-lg-1 col-md-1 col-1">
                        <a class="alphabet" asp-action="DoctorFind" asp-controller="Services" asp-route-st="x">X</a>
                    </div><div class="col-lg-1 col-md-1 col-1">
                        <a class="alphabet" asp-action="DoctorFind" asp-controller="Services" asp-route-st="i">İ</a>
                    </div><div class="col-lg-1 col-md-1 col-1">
                        <a class="alphabet" asp-action="DoctorFind" asp-controller="Services" asp-route-st="j">J</a>
                    </div><div class="col-lg-1 col-md-1 col-1">
                        <a class="alphabet" asp-action="DoctorFind" asp-controller="Services" asp-route-st="k">K</a>
                    </div><div class="col-lg-1 col-md-1 col-1">
                        <a class="alphabet" asp-action="DoctorFind" asp-controller="Services" asp-route-st="q">Q</a>
                    </div><div class="col-lg-1 col-md-1 col-1">
                        <a class="alphabet" asp-action="DoctorFind" asp-controller="Services" asp-route-st="l">L</a>
                    </div><div class="col-lg-1 col-md-1 col-1">
                        <a class="alphabet" asp-action="DoctorFind" asp-controller="Services" asp-route-st="m">M</a>
                    </div><div class="col-lg-1 col-md-1 col-1">
                        <a class="alphabet" asp-action="DoctorFind" asp-controller="Services" asp-route-st="n">N</a>
                    </div><div class="col-lg-1 col-md-1 col-1">
                        <a class="alphabet" asp-action="DoctorFind" asp-controller="Services" asp-route-st="o">O</a>
                    </div><div class="col-lg-1 col-md-1 col-1">
                        <a class="alphabet" asp-action="DoctorFind" asp-controller="Services" asp-route-st="ö">Ö</a>
                    </div><div class="col-lg-1 col-md-1 col-1">
                        <a class="alphabet" asp-action="DoctorFind" asp-controller="Services" asp-route-st="p">P</a>
                    </div><div class="col-lg-1 col-md-1 col-1">
                        <a class="alphabet" asp-action="DoctorFind" asp-controller="Services" asp-route-st="r">R</a>
                    </div><div class="col-lg-1 col-md-1 col-1">
                        <a class="alphabet" asp-action="DoctorFind" asp-controller="Services" asp-route-st="s">S</a>
                    </div><div class="col-lg-1 col-md-1 col-1">
                        <a class="alphabet" asp-action="DoctorFind" asp-controller="Services" asp-route-st="ş">Ş</a>
                    </div><div class="col-lg-1 col-md-1 col-1">
                        <a class="alphabet" asp-action="DoctorFind" asp-controller="Services" asp-route-st="t">T</a>
                    </div><div class="col-lg-1 col-md-1 col-1">
                        <a class="alphabet" asp-action="DoctorFind" asp-controller="Services" asp-route-st="u">U</a>
                    </div><div class="col-lg-1 col-md-1 col-1">
                        <a class="alphabet" asp-action="DoctorFind" asp-controller="Services" asp-route-st="ü">Ü</a>
                    </div><div class="col-lg-1 col-md-1 col-1">
                        <a class="alphabet" asp-action="DoctorFind" asp-controller="Services" asp-route-st="v">V</a>
                    </div><div class="col-lg-1 col-md-1 col-1">
                        <a class="alphabet" asp-action="DoctorFind" asp-controller="Services" asp-route-st="y">Y</a>
                    </div><div class="col-lg-1 col-md-1 col-1">
                        <a class="alphabet" asp-action="DoctorFind" asp-controller="Services" asp-route-st="z">Z</a>
                    </div>
                </div>

                <div class="row mt-5 body_content">
                    @foreach (var item in Model.Data)
                    {
                        string type = string.Empty;

                        if (item.LevelType == 1)
                        {
                            type = "Dr.";
                        }
                        else if (item.LevelType == 2)
                        {
                            type = "T.e.c.";
                        }
                        else if (item.LevelType == 0)
                        {
                            type = string.Empty;
                        }
                        else
                        {
                            return;
                        }

                        <div class="col-lg-4 col-md-6 col-sm-6">
                            <div class="our-doctor">
                                <a class="doctor-img" href="243-dr-altay-hsnov.html">
                                    <div class="overlay"></div>
                                    @if (item.Picture is null)
                                    {
                                        if (item.Sex == 1)
                                        {
                                            <img src="~/indexlayout/uploads/posts/2020-03/1584355056_man.png" alt="@item.Name">
                                        }
                                        else
                                        {
                                            <img src="~/indexlayout/uploads/posts/2020-03/1584360828_woman.png" alt="@item.Name">
                                        }

                                    }
                                    else
                                    {
                                        <img src="~/indexlayout/uploads/posts/2020-03/@item.Picture" alt="@item.Name">
                                    }

                                </a>

                                <div class="info-doctor">
                                    <a href="243-dr-altay-hsnov.html" class="doc-name">@type@item.Name</a>
                                    <span>@item.DoctorLevel</span>
                                    <a asp-action="DoctorsInfo" asp-controller="Services" asp-route-doctor="@item.Id">Daha ətraflı</a>
                                </div>
                            </div>
                        </div>

                    }









                </div>
                <div class="loadcontent">
                    <div class="d-flex justify-content-center " style="display:none">
                        <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                            <span class="sr-only">Loading...</span>
                        </div>
                    </div>
                </div>
              
            </div>
        </div>
    </section>
</div>

@section Scripts{ 

<script>
    
    var pagecount = 0;
    var scrollocation = 500;
    var numberpagetotal = parseInt($("#numberofpages").val());


    $(window).scroll(function () {
        if (numberpagetotal >= pagecount) {
            console.log(Math.ceil($(window).scrollTop()) + "  " + $(document).height() + " " + $(window).height())
            if (Math.ceil($(window).scrollTop()) + scrollocation + $(window).height() >= $(document).height()) {

                if (scrollocation != 400) {
                    scrollocation -= 100;
                }
                else {
                    scrollocation = 400;
                }

                pagecount += 1;
                var container = $(".body_content");
                $(".loadcontent").show()
                loadMoreData(pagecount);
                
            }

        }
        else {
            $(".loadcontent").hide()
        }
    
    });

    function loadMoreData(pageCount) {
        $.get("/Services/DoctorsPartial?page=" + pagecount, function (data) {
            $(".body_content").append(data)
        })
       
    };
</script>

}

IstanbulNsApp/IstanbulNsApp/Views/Services/DoctorsPartial.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = "";
}
@model IstanbulNsApp.ViewModels.DoctorViewModel

@foreach (var item in Model.Data)
{
    string type = string.Empty;

    if (item.LevelType == 1)
    {
        type = "Dr.";
    }
    else if (item.LevelType == 2)
    {
        type = "T.e.c.";
    }
    else if (item.LevelType == 0)
    {
        type = string.Empty;
    }
    else
    {
        return;
    }
    <div class="col-lg-4 col-md-6 col-sm-6">
        
        <div class="our-doctor">
            <a class="doctor-img" href="243-dr-altay-hsnov.html">
                <div class="overlay"></div>
                @if (item.Picture is null)
                {
                    if (item.Sex == 1)
                    {
                        <img src="~/indexlayout/uploads/posts/2020-03/1584355056_man.png" alt="@item.Name">
                    }
                    else
                    {
                        <img src="~/indexlayout/uploads/posts/2020-03/1584360828_woman.png" alt="@item.Name">
                    }

                }
                else
                {
                    <img src="~/indexlayout/uploads/posts/2020-03/@item.Picture" alt="@item.Name">
                }

            </a>

            <div class="info-doctor">
                <a href="243-dr-altay-hsnov.html" class="doc-name">@type@item.Name</a>
                <span>@item.DoctorLevel</span>
                <a asp-action="DoctorsInfo" asp-controller="Services" asp-route-doctor="@item.Id">Daha ətraflı</a>
            </div>
        </div>
    </div>
}

IstanbulNsApp/IstanbulNsApp/Views/Services/Index.cshtml
 <!-- End Header -->
@model IstanbulNsApp.Resources.DTO.ServiceInfo
<div id='dle-content'>
    <link rel="stylesheet" href="../use.fontawesome.com/releases/v5.7.2/css/all.css"
          integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link rel="stylesheet" href="~/indexlayout/css/tedbirler-etrafli.css">

    <section id="doctor-main">
        <div class="overlay-service"></div>
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="section-heading">
                        <h3>TƏDBİRLƏR</h3>
                    </div>
                </div>
            </div>
        </div>
    </section>




    <section id="more-event">
        <div class="container-fluid">
            <div class="container">
                <div class="row">
                    <div class="col-lg-3 col-md-4 col-sm-12 col-12">
                        @await Component.InvokeAsync("Services")
                    </div>

                    <div class="col-lg-9 col-md-8 col-sm-12 col-12">
                        <div id="read-event">
                            <h3>@Model.Name</h3>
                            @if (Model.Picture is null)
                            {
                                <img src="~/indexlayout/images/notfoundpicture.jpg" alt="@Model.Name">
                            }
                            else
                            {
                                <img src="~/indexlayout/images/@Model.Picture" alt="@Model.Name">
                            }

                            <div>
                                <p>
                                    @Model.Info
                                    <br />
                                    @foreach (var item in Model.Doctors)
                                    {

                                        <br />
                                        @(item.Name+"-"+item.DoctorLevel)
                                        <br />
                                    }
                                </p>





                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="hekimlerimiz">
            <div class="container">
                <div class="text-center">
                    <h3>HƏKİMLƏRİMİZ</h3>
                    <p>
                        Yüksək ixtisaslı, təcrübəli və qayğıkeş həkimlərimiz sağlamlığınızın qorunması üçün sizə
                        keyfiyyətli tibbi yardım göstərməyə hər zaman hazırdır! Onların qəbuluna saytımızdan yazıla
                        bilərsiniz.
                    </p>
                </div>

                <div class="row">
                    @foreach (var doctor in Model.Doctors)
                    {
                        string type = string.Empty;

                        if (doctor.LevelType == 1)
                        {
                            type = "Dr.";
                        }
                        else if (doctor.LevelType == 2)
                        {
                            type = "T.e.c.";
                        }
                        else if (doctor.LevelType == 0)
                        {
                            type = string.Empty;
                        }
                        else
                        {
                            return;
                        }
                        <div class="col-lg-4 col-md-6 col-sm-6 margin-top-30">
                            <div class="our-doctor">
                                <a class="doctor-img" href="238-dr-bhruz-mmmdov.html">
                                    <div class="overlay"></div>
                                    @if (doctor.Picture is null)
                                    {
                                        if (doctor.Sex == 1)
                                        {
                                            <img src="~/indexlayout/uploads/posts/2020-03/1584355056_man.png" alt="@doctor.Name">
                                        }
                                        else
                                        {
                                            <img src="~/indexlayout/uploads/posts/2020-03/1584360828_woman.png" alt="@doctor.Name">
                                        }

                                    }
                                    else
                                    {
                                        <img src="~/indexlayout/uploads/posts/2020-03/@doctor.Picture" alt="@doctor.Name">
                                    }

                                </a>

                                <div class="info-doctor">
                                    <a href="" class="doc-name">@type@doctor.Name</a>
                                    <span class="professional">@doctor.DoctorLevel
                                    </span>
                                    <a asp-controller="OnlineTurn" asp-action="Index" asp-route-doctor="@doctor.Id">QƏBULUNA YAZILMAQ</a>
                                </div>
                            </div>
                        </div>
                    }


                </div>
            </div>
        </div>
    </section>